/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:54159f79-2b6e-4b82-b257-5eeb3914a61b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8Nfw0G9B3",
    "aws_user_pools_web_client_id": "dc9700ltumjsf79k7d3ebbkls",
    "oauth": {}
};


export default awsmobile;
